spring.application.name=carrent
server.port=8080
spring.profiles.active=hibernate

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL DataSource
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging
logging.level.root=WARN
logging.level.carrent=INFO

